### ISSUE TITLE
Project talks about a metal pipe, but i dont see any.

### ISSUE THREAD

**Issue by Ch4t0n** [ChicknFish/MetalPipe#1]
# Ok, hear me out..
This could be due to the metal pipe not existing yet but I digress. This could be the most weirdest conspiracy theory I'm about to say but i think the metal pipe was stolen by aliens.

## My thesis:
Partial left over of _bread crumbs_ were left over so it has to be them. They are named "**Intergalactica B3**", a specie known for their intelligence yet they have a potent stupidity as well.

## Conclusion
The metal pipe needs to be rescued! This will be an issue until the metal pipe will be found!

**Comment by Yenaek** [comment]
![](https://i.imgflip.com/7w6fyo.jpg)

**Comment by Ch4t0n** [comment]
nvm
